//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Node
{


	private string id;
	private string label;

	private float x;
	private float y;
	private float z;

	private float size;

	private int r;
	private int g;
	private int b;

	public Node (string id, string label)
	{
		this.id = id;
		this.label = label;
		x = 0;
		y = 0;
		z = 0;

		size = 10;

		r = 120;
		g = 120;
		b = 120;
	}

	public void setPosition(float x,float y,float z){
		this.x = x;
		this.y = y;
		this.z = z;
	}

	public void setSize(float size){
		this.size = size;
	}

	public void setColor(int r,int g,int b){
		this.r = r;
		this.g = g;
		this.b = b;
	}

	public Color getColor ()
	{
		return new Color (((float)r)/255,((float)g)/255,((float)b)/255);
	}

	public string getId(){
		return id;
	}

	public Vector3 getPosition(){
		return new Vector3 (x/100,y/100,z/100);
	}
	public string getLabel (){
		return label;
	}

	public Vector3 getSize (){
		return new Vector3(size/100,size/100,size/100);
	}

	public override string ToString ()
	{
		return string.Format ("[Node] : {0} {1},{2},{3}",label,r/255.0,g/255.0,b/255.0);
	}
}


